"""Increase file_type column length

Revision ID: 985a50b1c668
Revises: 66fef7370e36
Create Date: 2025-12-07 09:57:18.793323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985a50b1c668'
down_revision: Union[str, Sequence[str], None] = '66fef7370e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_comment='MIME type (e.g., application/pdf)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_comment='MIME type (e.g., application/pdf)',
               existing_nullable=False)
    # ### end Alembic commands ###
