"""add cv_analyses table

Revision ID: a4cd1173eb16
Revises: a8769719cbf7
Create Date: 2025-12-07 13:27:05.088589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4cd1173eb16'
down_revision: Union[str, Sequence[str], None] = 'a8769719cbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsed_cv_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False, comment='Overall CV quality score'),
    sa.Column('completeness_score', sa.Integer(), nullable=False, comment='How complete the CV is'),
    sa.Column('quality_score', sa.Integer(), nullable=False, comment='Professional quality score'),
    sa.Column('ats_score', sa.Integer(), nullable=False, comment='ATS-friendliness score'),
    sa.Column('strengths', sa.JSON(), nullable=False, comment='List of CV strengths'),
    sa.Column('weaknesses', sa.JSON(), nullable=False, comment='List of CV weaknesses'),
    sa.Column('suggestions', sa.JSON(), nullable=False, comment='Improvement suggestions with priority'),
    sa.Column('skill_analysis', sa.JSON(), nullable=False, comment='Detailed skill breakdown and gaps'),
    sa.Column('experience_analysis', sa.JSON(), nullable=False, comment='Career progression analysis'),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parsed_cv_id'], ['parsed_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_analyses_id'), 'cv_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_cv_analyses_parsed_cv_id'), 'cv_analyses', ['parsed_cv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_analyses_parsed_cv_id'), table_name='cv_analyses')
    op.drop_index(op.f('ix_cv_analyses_id'), table_name='cv_analyses')
    op.drop_table('cv_analyses')
    # ### end Alembic commands ###
