"""added_updated_at_and_indexes_to_job_posts

Revision ID: ca45b3353018
Revises: 6f834ce70fed
Create Date: 2025-11-26 22:07:50.794526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca45b3353018'
down_revision: Union[str, Sequence[str], None] = '6f834ce70fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_job_posts_company'), 'job_posts', ['company'], unique=False)
    op.create_index(op.f('ix_job_posts_job_type'), 'job_posts', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_posts_location'), 'job_posts', ['location'], unique=False)
    op.create_index(op.f('ix_job_posts_title'), 'job_posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_posts_title'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_location'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_job_type'), table_name='job_posts')
    op.drop_index(op.f('ix_job_posts_company'), table_name='job_posts')
    op.drop_column('job_posts', 'updated_at')
    # ### end Alembic commands ###
